CREATE TABLE IF NOT EXISTS trace_record (
  id BIGINT NOT NULL AUTO_INCREMENT,
  correlation_id VARCHAR(255),
  channel_id VARCHAR(255),
  api_name VARCHAR(255),
  app_name VARCHAR(255),
  status VARCHAR(20),
  http_series VARCHAR(3),
  http_status_code INT,
  request_payload LONGTEXT,
  channel_payload LONGTEXT,
  core_payload LONGTEXT,
  core_response LONGTEXT,
  channel_response LONGTEXT,
  request_received_latency_ms INT,
  external_latency_ms INT,
  total_latency_ms INT,
  requesttimestamp DATETIME(6) NOT NULL,
  PRIMARY KEY (id),
  KEY idx_trace_record_requesttimestamp (requesttimestamp),
  KEY idx_trace_record_requesttimestamp_status (requesttimestamp, status),
  KEY idx_trace_record_requesttimestamp_http_series (requesttimestamp, http_series),
  KEY idx_trace_record_requesttimestamp_http_status_code (requesttimestamp, http_status_code),
  KEY idx_trace_record_scope_status (requesttimestamp, app_name, api_name, status),
  KEY idx_trace_record_scope_http_series (requesttimestamp, app_name, api_name, http_series),
  KEY idx_trace_record_api_name (api_name),
  KEY idx_trace_record_app_name (app_name),
  KEY idx_trace_record_correlation_id (correlation_id),
  KEY idx_trace_record_channel_id (channel_id)
);
